### ISSUE TITLE
Invalid CSS after "i.icon.stopwatch.": expected class name, was "20:before"

### ISSUE THREAD

**Issue by birthdaycorp** [fomantic/Fomantic-UI-SASS#12] opened 2021-02-21 18:31 UTC
When importing semantic-ui in my application.css file, i get this error: `Invalid CSS after "i.icon.stopwatch.": expected class name, was "20:before"`. What causes this?

**Comment by lubber-de** [comment] 2021-02-21 20:27
This was fixed in fomantic-ui 2.8.7 by https://github.com/fomantic/Fomantic-UI/pull/1546
This port just needs an update 😉

**Comment by lubber-de** [comment] 2021-02-21 20:30
Duplicate of #11

**Comment by shanecav84** [comment] 2021-03-04 01:30
Thanks for adding the duplicate tag, @lubber-de.

**Comment by shanecav84** [comment] 2021-03-04 01:30
I've released 2.8.7 which hopefully fixes the issue.

**Closed as completed by shanecav84** 2021-03-04 01:30 UTC
Labels: bug, duplicate
